/* =============================================
   PORTFOLIO DEFAULT PROJECTS
   Managed via admin.html — edit there, not here.
   ============================================= */

window.PORTFOLIO_PROJECTS = [
    {
        id: 'default-cardapio',
        title: 'Cardápio+',
        badge: 'SAAS',
        categories: ['saas', 'dashboards'],
        desc: 'Criei a experiência completa do Cardápio+, da identidade visual ao produto digital.',
        client: 'Cardápio+',
        services: 'UI/UX Design, Branding',
        industry: 'Food & Tech',
        country: 'Brasil',
        thumbnail: './img/projetos/Cardapio-view.png',
        img: './img/projetos/Cardapio-projeto.png',
        link: '',
        tags: ['FIGMA', 'BLENDER'],
        videos: [],
    },
    {
        id: 'default-woit',
        title: 'Woit Detailer',
        badge: 'WEBSITE',
        categories: ['website'],
        desc: 'Criei a landing page completa da Woit Detailer, focada em conversão e identidade visual premium.',
        client: 'Woit Detailer',
        services: 'UI/UX Design, Landing Page',
        industry: 'Automotive',
        country: 'Brasil',
        thumbnail: './img/projetos/Woit-view.png',
        img: './img/projetos/Woit-LP.png',
        link: '',
        tags: ['FIGMA', 'FRAMER'],
        videos: [],
    },
    {
        id: 'default-3print',
        title: '3Print',
        badge: 'SAAS',
        categories: ['saas'],
        desc: 'Criei a identidade visual e a experiência digital completa da 3Print, focando em conversão e presença de marca.',
        client: '3Print',
        services: 'UI/UX Design, Branding',
        industry: '3D Printing',
        country: 'Brasil',
        thumbnail: './img/Projetos/3Print-view.png',
        img: './img/Projetos/3print-LP.png',
        link: '',
        tags: ['FIGMA', 'BRANDING'],
        videos: [],
    },
    {
        id: 'default-vivo',
        title: 'Vivo Empresas',
        badge: 'WEBSITE',
        categories: ['website'],
        desc: 'Criei peças de comunicação digital e experiências de UX para a linha Vivo Empresas.',
        client: 'Vivo Empresas',
        services: 'UI/UX Design, Motion',
        industry: 'Telecom',
        country: 'Brasil',
        thumbnail: './img/projetos/VivoEmpresas-view.png',
        img: './img/projetos/VivoEmpresas-LP.png',
        link: '',
        tags: ['FIGMA', 'MOTION', 'BLENDER'],
        videos: ['./img/projetos/VivoChip-video.mp4', './img/projetos/VivoSMP-video.mp4'],
    },
    {
        id: 'default-g3',
        title: 'G3 Telemedicina',
        badge: 'WEBSITE',
        categories: ['website'],
        desc: 'Criei a landing page da G3 Telemedicina, comunicando credibilidade e facilitando a conversão de novos pacientes.',
        client: 'G3 Telemedicina',
        services: 'UI/UX Design, Landing Page',
        industry: 'Health & Tech',
        country: 'Brasil',
        thumbnail: './img/projetos/G3telemedicina-view.png',
        img: './img/projetos/G3telemedicina-LP.png',
        link: '',
        tags: ['FIGMA', 'FRAMER'],
        videos: [],
    },
];
